package model;

/**
 * Created by chand on 11/6/16.
 */
public class Customer {

    public String id;
    public String customerId;
    public int age;
    public String gender;
    public String maritalStatus;
    public String numberHouseHolds;
    public String numberChild;
    public String zipcode;
    public String residentialStatus;
    public String education;
    public String occupation;
    public String industryType;
    public String currentDesignation;
    public int timeInBusiness;
    public String currentEmploymentStatus;
    public String typeOfAccommodation;
    public String numberOfOwnHouses;
    public String usageOfHouse;
    public String numberOfCars;
    public String incomeFromBusinessOrProfession;
    public String otherIncome;
    public double annualIncome ;
    public String monthlyExpenditure ;
    public String annualExpenditure ;
    public String annualDisposableIncome ;
    public String monthlyAvgDisposableIncome ;
    public double totalFamilyIncomeAnnual ;
    public String totalFamilyExpenditureAnnual ;
    public String totalDisposableIncomeAnnual ;
    public String totalAssets;
    public String totalLiabilities ;
    public double currentAmtOfDebt ;
    public String totalNumberOfLoans ;
    public String totalAmountOfLoans ;
    public String numberOfLoansWithOutstandingBalance ;
    public String outstandingBalanceOfLoan ;
    public String mostRecentLoan;
    public String ageOfOldestLoan ;
    public int loanLast1Mto3M ;
    public String loanLast3Mto6M ;
    public String loanLast6Mto12M ;
    public String totalNumberOfEducationLoan ;
    public String totalAmountOfEducationLoan ;
    public String mostRecentEducationLoan ;
    public String educationLoanLast1Mto3M ;
    public String educationLoanLast3Mto6M ;
    public String educationLoanLast6Mto12M ;
    public String totalNumberOfHomeLoan ;
    public String totalAmountOfHomeLoan ;
    public String mostRecentHomeLoan ;
    public String homeLoanLast1Mto3M ;
    public String homeLoanLast3Mto6M ;
    public String homeLoanLast6Mto12M ;
    public String totalNumberOfCarLoan ;
    public String totalAmountOfCarLoan ;
    public String mostRecentCarLoan ;
    public String carLoanLast1Mto3M ;
    public String carLoanLast3Mto6M ;
    public String carLoanLast6Mto12M ;
    public String totalNumberOfPersonalLoan ;
    public String totalAmountOfPersonalLoan ;
    public String mostRecentPersonalLoan ;
    public String personalLoanLast1Mto3M ;
    public String personalLoanLast3Mto6M ;
    public String personalLoanLast6Mto12M ;
    public String totalNoCreditCards ;
    public String totalCreditLimit ;
    public String creditLimitUtilizationPercentage ;
    public String mostRecentCreditCard ;
    public String ageOfFirstCreditCard ;
    public String numbereOfPastDue ;
    public String totalAmountofPastDue ;
    public String creditCardLast1Mto3MExtra;
    public String creditCardLast3Mto6MExtra;
    public String creditCardLast6Mto12MExtra;
    public String numberOfDefaultAndLegalAction ;
    public String totalAmountofDefaultAndLegalAction ;
    public String lastDateOfDefaultAndLegalAction ;
    public String numberLoansOfDefaultAndLegalAction ;
    public String numberOfInquiriesInPast12M ;
    public String ficoScore ;
    public String bankInternalScore ;
    public String totalNumberOfCardsBank;
    public String totalCreditLimitBank ;
    public String typeOfCreditCardBank ;
    public String dateOfFirstCreditCardIssuedBank;
    public String ageOfFirstCreditCardInDaysBank;
    public String mostRecentCreditCardBank;
    public int creditCardLast1Mto3M;
    public int creditCardLast3Mto6M;
    public int creditCardLast6Mto12M;
    public String mostUsageOfCreditCard12MBank;
    public String currentBalance ;
    public String availableCreditBank;
    public String minimumPaymentDueBank;
    public String averageExpenditurePerMonthBank;
    public String creditLimitUtilizationBank;
    public String daysBillingCycleBank;
    public String annualPercentageRateAprBank;
    public String averageAnnualFeeBank;
    public String balanceTransferFeeInformationBank;
    public String dateOfLastTransactionBank;
    public int numberOfTransactions12MBank;
    public int numberOfTransactions6MBank;
    public int numberOfTransactions3MBank;
    public String periodOfMaxTransactionBank;
    public String pastDueCreditCardBank;
    public String dateOfPastDueBank;
    public String totalNumberOfLoansBank;
    public String totalAmountOfLoanBank;
    public String outstandingAmountBank;
    public String exposureLimitBank;
    public String exposureOfSecuredLoanBank;
    public double exposureExceedsBank;
    public String firstActiveLoanBank;
    public String ageOfFirstLoanBank;
    public String totalAmountOfLoansBank;
    public String mostRecentLoanBank;
    public String loanLast1Mto3MBank;
    public String loanLast3Mto6MBank;
    public String loanLast6Mto12MBank;
    public String totalNumberEducationLoanBank;
    public String totalAmountEducationLoanBank;
    public String mostRecentEducationLoanBank;
    public int educationLoanLast1Mto3MBank;
    public int educationLoanLast3Mto6MBank;
    public int educationLoanLast6Mto12MBank;
    public String firstEducationLoanBank;
    public String ageOfFirstEducationLoanBank;
    public String interestOnEducationLoanBank;
    public String totalNumberHomeLoanBank;
    public String totalAmountOfHomeLoanBank;
    public String mostRecentHomeLoanBank;
    public int homeLoanLast1Mto3MBank;
    public int homeLoanLast3Mto6MBank;
    public int homeLoanLast6Mto12MBank;
    public String firstHomeLoanDateBank;
    public String ageOfFirstHomeLoanBank;
    public String numberOfFixedRateLoanBank;
    public String numberOfVariableRateLoanBank;
    public String maxInterestChargedBank;
    public String minInterestChargedBank;
    public String averageInterestChargedBank;
    public String totalNumberCarLoanBank;
    public String totalAmountCarLoanBank;
    public String firstCarLoanBank;
    public String ageFirstCarLoanBank;
    public String mostRecentCarLoanBank;
    public int carLoanLast1Mto3MBank;
    public int carLoanLast3Mto6MBank;
    public int carLoanLast6Mto12MBank;
    public String maxInterestCarLoanBank;
    public String minInterestChargedCarloanBank;
    public String avgInterestchargedCarloanBank;
    public String totalNoPersonalLoanBank;
    public String totalAmtPersonalLoanBank;
    public String firstPersonalLoanBank;
    public String ageofFirstPersonalLoanBankInDays;
    public String mostRecentPersonalLoanBank;
    public int personalLoanLast1M3MBank;
    public String personalLoanLast3M6MBank;
    public String personalLoanLast6M12MBank;
    public String maxInterestChargedPersonalLoanBank;
    public String minInterestChargedPersonalLoanBank;
    public String avgInterestChargedPersonalLoanBank;
    public String purposeofPersonalLoanBank;
    public String numberOfCreditCardsPerLoansLast1YrBank;
    public String numberOfSavingAccountsBank;
    public String firstSavingsAccountBank;
    public String ageofFirstAccountInDaysBank;
    public String lastOpeningDateAccountBank;
    public int numberOfSavingsAccountsInLast1Mto3MBank;
    public int numberOfSavingsAccountsLast3Mto6MBank;
    public int numberOfSavingsAccountsLast6Mto12MBank;
    public String currentBalanceSavingsBank;
    public String closingBalLastyrBank;
    public String dateofLastTransactionBank;
    public String noTransactions1M3MBank;
    public String noTransactions3M6MBank;
    public String noofTransactions6M12MBank;
    public String noFixedDepositsBank;
    public String totalAmtFixedDepositBank;
    public String no_FixedDeposits_LastYrBank;
    public String maxInterest_FixedDepositBank;
    public String minInterest_FixedDepositBank;
    public String avgInterest_FixedDepositBank;
    public String noofInsurancePoliciesBank;
    public String totalPremiumBank;
    public String totalSumAssuredBank;
    public String noTermInsuranceBank;
    public String lastTermInsuranceBank;
    public String termInsurance1M3MBank;
    public String termInsurance3M6MBank;
    public String termInsurance6M12MBank;
    public String totalSumAssuredTermInsurancePolicyBank;
    public String totalEndowmentPolicyBank;
    public String totalSumAssuredEndowmentPolicyBank;
    public String lastEndowmentPolicyBank;
    public int endowmentPolicy1M3MBank;
    public int endowmentPolicy3M6MBank;
    public int endowmentPolicy6M12MBank;
    public String noPensionPlanBank;
    public String totalSumAssuredPensionPlanBank;
    public String lastPensionPlanBank;
    public int pensionPlan1M3MBank;
    public int pensionPlan3M6MBank;
    public int pensionPlan6M12MBank;
    public String noofDematAccountBank;
    public String avgNoofTransaction_DematBank;
    public String noMutualFundsBank;
    public String totalAmtMutualFundBank;
    public String noMutualFundLastYrBank;
    public String noLoansDefaultLegalActionBank;
    public String totalAmtDefaultLegalActionBank;
    public String lastDateofDefaultLegalActionBank;
    public String avgNo_visit12MBank;
    public String channelofTransactionBank;
    public String dateofLastTransaction;
    public int totalNoTransactions1M3MBank;
    public int totalNoTransactions3M12MBank;
    public int totalNoTransactions6M12MBank;
    public String totalNoTransactionHotelBookingBank;
    public String totalNoTransactionTrainTicketsBank;
    public String totalNoTransactionFlightTicketsBank;
    public String totalNoTransactionTaxiBank;
    public String totalNoBookingTravelBank;
    public String totalNoTransactionBillPaymentBank;
    public String totalNoTransactionRetailshoppingBank;
    public String totalNoTransactionMoviesBank;
    public String totalNoTransactionGroceryShoppingBank;
    public String totalNoTransactionFuelBank;
    public String everApproachedForPromotionBank;
    public String promotionChannelBank;
    public String typeofProductRecentlySoldBank;
    public String totalNoofNewProductsold12MBank;
    public String customerApproachableThroughPhoneBank;
    public String customerApproachableThroughMailBank;
    public String noofTimesRepresentativesendtoCustomerBank;
    public String customerFeedbackBank;
    public String customerIssueBank;
    public boolean loyaltyStatus;
    public double yrsRelationshipCustomerBank;
    public String avgSpendingPerYearBank;
    public String facilitiesGivenByBank;
    public String dateOfBirth;
    public String weddinganniversary;
    public String maxTransactioncategory;

}
